# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.100.0"

default_platform :ios

platform :ios do
  desc "Increment build number"
  lane :bump_version do
    increment_build_number(build_number: number_of_commits)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    cocoapods
    bump_version
    gym(scheme: "Foodancy") # Build your app - more options available
    pilot(skip_waiting_for_build_processing: true)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    gym(scheme: "Foodancy") # Build your app - more options available
    deliver(force: true)
  end
end

